/* eslint-disable */
/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

export type Name = string
export type Message = string
export type RootModelStr = string
export type Id = (string | null)
export type Title = string
export type Id1 = string
export type Role = string
export type Content = string
export type Createdat = (string | null)
export type Toolcalls = (ToolCall[] | null)
export type Id2 = string
export type Toolname = string
export type Toolresult = (string | null)
export type Iscompleted = (boolean | null)
export type Messages = ChatMessage[]
export type Model = (string | null)
export type Createdat1 = (string | null)
export type Updatedat = (string | null)
export type Id3 = (string | null)
export type Title1 = (string | null)
export type Model1 = (string | null)
export type Id4 = string
export type Title2 = (string | null)
export type Model2 = (string | null)
export type Messages1 = (ChatMessage[] | null)
export type Id5 = string
export type RootModelNoneType = null

/**
 * Commands Input and Output Schemas
 */
export interface Commands {
greet: {
input: Person
output: Greeting
}
get_version: {
input: void | undefined
output: RootModelStr
}
get_all_chats: {
input: void | undefined
output: AllChatsData
}
create_chat: {
input: CreateChatInput
output: ChatData
}
update_chat: {
input: UpdateChatInput
output: ChatData
}
delete_chat: {
input: ChatId
output: RootModelNoneType
}
get_chat: {
input: ChatId
output: RootModelDictStrAny
}
}
export interface Person {
name: Name
}
export interface Greeting {
message: Message
}
export interface AllChatsData {
chats: Chats
}
export interface Chats {
[k: string]: ChatData
}
export interface ChatData {
id?: Id
title: Title
messages?: Messages
model?: Model
createdAt?: Createdat1
updatedAt?: Updatedat
}
export interface ChatMessage {
id: Id1
role: Role
content: Content
createdAt?: Createdat
toolCalls?: Toolcalls
}
export interface ToolCall {
id: Id2
toolName: Toolname
toolArgs: Toolargs
toolResult?: Toolresult
isCompleted?: Iscompleted
}
export interface Toolargs {
[k: string]: unknown
}
export interface CreateChatInput {
id?: Id3
title?: Title1
model?: Model1
}
export interface UpdateChatInput {
id: Id4
title?: Title2
model?: Model2
messages?: Messages1
}
export interface ChatId {
id: Id5
}
export interface RootModelDictStrAny {
[k: string]: unknown
}
