/* eslint-disable */
/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

export type Name = string
export type Message = string
export type RootModelStr = string
export type Provider = string
export type Modelid = string
export type Displayname = string
export type Isdefault = boolean
export type Models = ModelInfo[]
export type Provider1 = string
export type Apikey = (string | null)
export type Baseurl = (string | null)
export type Enabled = boolean
export type Providers = ProviderConfig[]
export type Provider2 = string
export type Apikey1 = (string | null)
export type Baseurl1 = (string | null)
export type Enabled1 = boolean
export type RootModelNoneType = null
export type Toolids = string[]
export type Toolids1 = string[]
export type Id = (string | null)
export type Title = string
export type Id1 = string
export type Role = string
export type Content = (string | ContentBlock[])
export type Type = string
export type Content1 = (string | null)
export type Id2 = (string | null)
export type Toolname = (string | null)
export type Toolargs = ({
[k: string]: unknown
} | null)
export type Toolresult = (string | null)
export type Iscompleted = (boolean | null)
export type Createdat = (string | null)
export type Toolcalls = (ToolCall[] | null)
export type Id3 = string
export type Toolname1 = string
export type Toolresult1 = (string | null)
export type Iscompleted1 = (boolean | null)
export type Messages = ChatMessage[]
export type Model = (string | null)
export type Createdat1 = (string | null)
export type Updatedat = (string | null)
export type Id4 = (string | null)
export type Title1 = (string | null)
export type Model1 = (string | null)
export type Provider3 = string
export type Modelid1 = string
export type Toolids2 = string[]
export type Instructions = string[]
export type Name1 = (string | null)
export type Description = (string | null)
export type Id5 = string
export type Title2 = (string | null)
export type Model2 = (string | null)
export type Id6 = string
export type Chatid = string
export type Toolids3 = string[]
export type Chatid1 = string
export type Provider4 = string
export type Modelid2 = string
export type Id7 = string
export type Name2 = (string | null)
export type Description1 = (string | null)
export type Category = (string | null)
export type Tools = ToolInfo[]
export type Toolids4 = string[]
export type Provider5 = string
export type Modelid3 = string
export type JavaScriptChannelIdChatEvent = string
export type Messages1 = {
[k: string]: unknown
}[]
export type Modelid4 = (string | null)
export type Chatid2 = (string | null)

/**
 * Commands Input and Output Schemas
 */
export interface Commands {
greet: {
input: Person
output: Greeting
}
get_version: {
input: void | undefined
output: RootModelStr
}
get_available_models: {
input: void | undefined
output: AvailableModelsResponse
}
get_provider_settings: {
input: void | undefined
output: AllProvidersResponse
}
save_provider_settings: {
input: SaveProviderConfigInput
output: RootModelNoneType
}
get_default_tools: {
input: void | undefined
output: DefaultToolsResponse
}
set_default_tools: {
input: SetDefaultToolsInput
output: RootModelNoneType
}
get_all_chats: {
input: void | undefined
output: AllChatsData
}
create_chat: {
input: CreateChatInput
output: ChatData
}
update_chat: {
input: UpdateChatInput
output: ChatData
}
delete_chat: {
input: ChatId
output: RootModelNoneType
}
get_chat: {
input: ChatId
output: RootModelDictStrAny
}
toggle_chat_tools: {
input: ToggleChatToolsInput
output: RootModelNoneType
}
update_chat_model: {
input: UpdateChatModelInput
output: RootModelNoneType
}
get_available_tools: {
input: void | undefined
output: AvailableToolsResponse
}
get_chat_agent_config: {
input: ChatId
output: ChatAgentConfigResponse
}
stream_chat: {
input: StreamChatRequest
output: RootModelNoneType
}
}
export interface Person {
name: Name
}
export interface Greeting {
message: Message
}
export interface AvailableModelsResponse {
models: Models
}
export interface ModelInfo {
provider: Provider
modelId: Modelid
displayName: Displayname
isDefault?: Isdefault
}
export interface AllProvidersResponse {
providers: Providers
}
export interface ProviderConfig {
provider: Provider1
apiKey?: Apikey
baseUrl?: Baseurl
enabled?: Enabled
}
export interface SaveProviderConfigInput {
provider: Provider2
apiKey?: Apikey1
baseUrl?: Baseurl1
enabled?: Enabled1
}
export interface DefaultToolsResponse {
toolIds: Toolids
}
export interface SetDefaultToolsInput {
toolIds: Toolids1
}
export interface AllChatsData {
chats: Chats
}
export interface Chats {
[k: string]: ChatData
}
export interface ChatData {
id?: Id
title: Title
messages?: Messages
model?: Model
createdAt?: Createdat1
updatedAt?: Updatedat
}
export interface ChatMessage {
id: Id1
role: Role
content: Content
createdAt?: Createdat
toolCalls?: Toolcalls
}
export interface ContentBlock {
type: Type
content?: Content1
id?: Id2
toolName?: Toolname
toolArgs?: Toolargs
toolResult?: Toolresult
isCompleted?: Iscompleted
}
export interface ToolCall {
id: Id3
toolName: Toolname1
toolArgs: Toolargs1
toolResult?: Toolresult1
isCompleted?: Iscompleted1
}
export interface Toolargs1 {
[k: string]: unknown
}
export interface CreateChatInput {
id?: Id4
title?: Title1
model?: Model1
agentConfig?: (AgentConfig | null)
}
export interface AgentConfig {
provider?: Provider3
modelId?: Modelid1
toolIds?: Toolids2
instructions?: Instructions
name?: Name1
description?: Description
}
export interface UpdateChatInput {
id: Id5
title?: Title2
model?: Model2
}
export interface ChatId {
id: Id6
}
export interface RootModelDictStrAny {
[k: string]: unknown
}
export interface ToggleChatToolsInput {
chatId: Chatid
toolIds: Toolids3
}
export interface UpdateChatModelInput {
chatId: Chatid1
provider: Provider4
modelId: Modelid2
}
export interface AvailableToolsResponse {
tools: Tools
}
export interface ToolInfo {
id: Id7
name?: Name2
description?: Description1
category?: Category
}
export interface ChatAgentConfigResponse {
toolIds: Toolids4
provider: Provider5
modelId: Modelid3
}
/**
 * Request model for stream_chat command.
 */
export interface StreamChatRequest {
channel: JavaScriptChannelIdChatEvent
messages: Messages1
modelId?: Modelid4
chatId?: Chatid2
[k: string]: unknown
}
