/* eslint-disable */
/**
 * This file was automatically generated by pytauri-gen-ts.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source commands API,
 * and run pytauri-gen-ts to regenerate this file.
 */

import { pyInvoke } from "tauri-plugin-pytauri-api";
import type { InvokeOptions } from "@tauri-apps/api/core";

import type { Commands } from "./_apiTypes.d.ts";

export async function greet(
    body: Commands["greet"]["input"],
    options?: InvokeOptions
): Promise<Commands["greet"]["output"]> {
    return await pyInvoke("greet", body, options);
}

export async function getVersion(
    body: Commands["get_version"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_version"]["output"]> {
    return await pyInvoke("get_version", body, options);
}

/**
 * Get list of available models based on configured providers.
 *
 * Checks both environment variables and database provider settings.
 *
 * Returns:
 *     List of available models with provider, modelId, displayName, and isDefault
 */
export async function getAvailableModels(
    body: Commands["get_available_models"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_available_models"]["output"]> {
    return await pyInvoke("get_available_models", body, options);
}

/**
 * Get all configured provider settings.
 *
 * Returns:
 *     List of provider configurations
 */
export async function getProviderSettings(
    body: Commands["get_provider_settings"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_provider_settings"]["output"]> {
    return await pyInvoke("get_provider_settings", body, options);
}

/**
 * Save or update provider settings.
 *
 * Args:
 *     body: Provider configuration to save
 *     app_handle: Tauri app handle
 */
export async function saveProviderSettings(
    body: Commands["save_provider_settings"]["input"],
    options?: InvokeOptions
): Promise<Commands["save_provider_settings"]["output"]> {
    return await pyInvoke("save_provider_settings", body, options);
}

/**
 * Get default tool IDs for new chats.
 *
 * Returns:
 *     List of default tool IDs
 */
export async function getDefaultTools(
    body: Commands["get_default_tools"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_default_tools"]["output"]> {
    return await pyInvoke("get_default_tools", body, options);
}

/**
 * Set default tool IDs for new chats.
 *
 * Args:
 *     body: Contains list of tool IDs to set as defaults
 *     app_handle: Tauri app handle
 */
export async function setDefaultTools(
    body: Commands["set_default_tools"]["input"],
    options?: InvokeOptions
): Promise<Commands["set_default_tools"]["output"]> {
    return await pyInvoke("set_default_tools", body, options);
}

/**
 * Get auto-title generation settings.
 *
 * Returns:
 *     Auto-title settings including enabled, prompt, and model configuration
 */
export async function getAutoTitleSettings(
    body: Commands["get_auto_title_settings"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_auto_title_settings"]["output"]> {
    return await pyInvoke("get_auto_title_settings", body, options);
}

/**
 * Save auto-title generation settings.
 *
 * Args:
 *     body: Auto-title settings to save
 *     app_handle: Tauri app handle
 */
export async function saveAutoTitleSettings(
    body: Commands["save_auto_title_settings"]["input"],
    options?: InvokeOptions
): Promise<Commands["save_auto_title_settings"]["output"]> {
    return await pyInvoke("save_auto_title_settings", body, options);
}

export async function getAllChats(
    body: Commands["get_all_chats"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_all_chats"]["output"]> {
    return await pyInvoke("get_all_chats", body, options);
}

export async function createChat(
    body: Commands["create_chat"]["input"],
    options?: InvokeOptions
): Promise<Commands["create_chat"]["output"]> {
    return await pyInvoke("create_chat", body, options);
}

export async function updateChat(
    body: Commands["update_chat"]["input"],
    options?: InvokeOptions
): Promise<Commands["update_chat"]["output"]> {
    return await pyInvoke("update_chat", body, options);
}

export async function deleteChat(
    body: Commands["delete_chat"]["input"],
    options?: InvokeOptions
): Promise<Commands["delete_chat"]["output"]> {
    return await pyInvoke("delete_chat", body, options);
}

export async function getChat(
    body: Commands["get_chat"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_chat"]["output"]> {
    return await pyInvoke("get_chat", body, options);
}

/**
 * Update active tools for a chat session.
 *
 * Args:
 *     body: Contains chatId and list of tool IDs to activate
 *     app_handle: Tauri app handle
 */
export async function toggleChatTools(
    body: Commands["toggle_chat_tools"]["input"],
    options?: InvokeOptions
): Promise<Commands["toggle_chat_tools"]["output"]> {
    return await pyInvoke("toggle_chat_tools", body, options);
}

/**
 * Switch the model/provider for a chat session.
 *
 * Args:
 *     body: Contains chatId, provider, and modelId
 *     app_handle: Tauri app handle
 */
export async function updateChatModel(
    body: Commands["update_chat_model"]["input"],
    options?: InvokeOptions
): Promise<Commands["update_chat_model"]["output"]> {
    return await pyInvoke("update_chat_model", body, options);
}

/**
 * Get list of all available tools.
 *
 * Returns:
 *     List of tool information (id, name, description, category)
 */
export async function getAvailableTools(
    body: Commands["get_available_tools"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_available_tools"]["output"]> {
    return await pyInvoke("get_available_tools", body, options);
}

/**
 * Get agent configuration for a chat (tools, provider, model).
 *
 * Args:
 *     body: Contains chatId
 *     app_handle: Tauri app handle
 *
 * Returns:
 *     Chat's agent configuration
 */
export async function getChatAgentConfig(
    body: Commands["get_chat_agent_config"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_chat_agent_config"]["output"]> {
    return await pyInvoke("get_chat_agent_config", body, options);
}

/**
 * Generate and update title for a chat based on its first message.
 *
 * Args:
 *     body: Contains chatId
 *     app_handle: Tauri app handle
 *
 * Returns:
 *     Dict with the new title or None if generation failed
 */
export async function generateChatTitle(
    body: Commands["generate_chat_title"]["input"],
    options?: InvokeOptions
): Promise<Commands["generate_chat_title"]["output"]> {
    return await pyInvoke("generate_chat_title", body, options);
}

/**
 * Cancel an active streaming run. Returns {cancelled: bool}
 */
export async function cancelRun(
    body: Commands["cancel_run"]["input"],
    options?: InvokeOptions
): Promise<Commands["cancel_run"]["output"]> {
    return await pyInvoke("cancel_run", body, options);
}

export async function streamChat(
    body: Commands["stream_chat"]["input"],
    options?: InvokeOptions
): Promise<Commands["stream_chat"]["output"]> {
    return await pyInvoke("stream_chat", body, options);
}

/**
 * Continue incomplete assistant message from where it stopped.
 */
export async function continueMessage(
    body: Commands["continue_message"]["input"],
    options?: InvokeOptions
): Promise<Commands["continue_message"]["output"]> {
    return await pyInvoke("continue_message", body, options);
}

/**
 * Create sibling message and retry generation.
 */
export async function retryMessage(
    body: Commands["retry_message"]["input"],
    options?: InvokeOptions
): Promise<Commands["retry_message"]["output"]> {
    return await pyInvoke("retry_message", body, options);
}

/**
 * Edit user message by creating sibling with new content.
 */
export async function editUserMessage(
    body: Commands["edit_user_message"]["input"],
    options?: InvokeOptions
): Promise<Commands["edit_user_message"]["output"]> {
    return await pyInvoke("edit_user_message", body, options);
}

/**
 * Switch active branch to different sibling.
 */
export async function switchToSibling(
    body: Commands["switch_to_sibling"]["input"],
    options?: InvokeOptions
): Promise<Commands["switch_to_sibling"]["output"]> {
    return await pyInvoke("switch_to_sibling", body, options);
}

/**
 * Get all sibling messages for navigation UI.
 */
export async function getMessageSiblings(
    body: Commands["get_message_siblings"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_message_siblings"]["output"]> {
    return await pyInvoke("get_message_siblings", body, options);
}
