/* eslint-disable */
/**
 * This file was automatically generated by pytauri-gen-ts.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source commands API,
 * and run pytauri-gen-ts to regenerate this file.
 */

import { pyInvoke } from "tauri-plugin-pytauri-api";
import type { InvokeOptions } from "@tauri-apps/api/core";

import type { Commands } from "./_apiTypes.d.ts";

export async function greet(
    body: Commands["greet"]["input"],
    options?: InvokeOptions
): Promise<Commands["greet"]["output"]> {
    return await pyInvoke("greet", body, options);
}

export async function getVersion(
    body: Commands["get_version"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_version"]["output"]> {
    return await pyInvoke("get_version", body, options);
}

export async function getAllChats(
    body: Commands["get_all_chats"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_all_chats"]["output"]> {
    return await pyInvoke("get_all_chats", body, options);
}

export async function createChat(
    body: Commands["create_chat"]["input"],
    options?: InvokeOptions
): Promise<Commands["create_chat"]["output"]> {
    return await pyInvoke("create_chat", body, options);
}

export async function updateChat(
    body: Commands["update_chat"]["input"],
    options?: InvokeOptions
): Promise<Commands["update_chat"]["output"]> {
    return await pyInvoke("update_chat", body, options);
}

export async function deleteChat(
    body: Commands["delete_chat"]["input"],
    options?: InvokeOptions
): Promise<Commands["delete_chat"]["output"]> {
    return await pyInvoke("delete_chat", body, options);
}

export async function getChat(
    body: Commands["get_chat"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_chat"]["output"]> {
    return await pyInvoke("get_chat", body, options);
}
